'use strict';

/**
 * Task 060 — Theo dõi phiếu đề xuất do hệ thống tự tạo.
 * Nguồn kỳ vọng: `resource/hdsd/hdsd04_1_canh_bao_ton_kho/tasks/060_theo_doi_phieu_tu_dong.md`.
 * Màn: `features/purchaseOrder/pages/StockRequestListPage.jsx` · route `/inventory/purchase-request`
 * API danh sách: `GET /stock-requests`.
 *
 * 🔴 Toàn bộ case CHỈ ĐỌC.
 *
 * 🚫 NGOÀI PHẠM VI auto test — hai lưu ý của tài liệu là logic chạy nền theo lịch, không kiểm
 *    được qua giao diện, và 🚫 không viết case giả vờ kiểm:
 *      1. Hệ thống chỉ tự sinh phiếu cho sản phẩm có ĐỦ CẢ định mức Min và Max; thiếu một trong
 *         hai thì bỏ qua và KHÔNG có thông báo nào.
 *      2. Sản phẩm đã nằm trong phiếu tự động chưa xử lý xong sẽ không được đưa vào phiếu mới.
 *    Muốn kiểm hai điều này phải chạy job và đối chiếu DB, thuộc phạm vi kiểm thử tích hợp.
 */

const { test, expect } = require('@playwright/test');
const { moTrang } = require('../../shared/auth/login');
const { settle, skipNoData } = require('./alert-page');

const ROUTE = '/inventory/purchase-request';
const API_LIST = '/stock-requests';

const rows = (page) => page.locator('.ant-table-tbody tr.ant-table-row');

async function openList(page) {
	const cho = page
		.waitForResponse((r) => r.url().includes(API_LIST) && r.request().method() === 'GET', {
			timeout: 60_000,
		})
		.catch(() => null);
	await moTrang(page, ROUTE, 'tct');
	await cho;
	await settle(page);
}

/** Chờ danh sách nạp lại do một thao tác lọc gây ra, trả về request đã gửi. */
/**
 * Chờ danh sách nạp lại do một thao tác lọc gây ra, trả về tham số đã gửi.
 *
 * 🔴 Màn này có HAI truy vấn dùng chung `GET /stock-requests`: danh sách chính (`size` = 10) và một
 *    truy vấn đếm phiếu giao thẳng (`size: 1, status: "SUPPLIER_CONFIRMED"` — dòng 251).
 *    Bắt lỏng theo URL là vớ phải truy vấn đếm, rồi kết luận sai rằng "bộ lọc không gửi tham số".
 *    Loại nó ra bằng `size` khác 1.
 */
async function locBy(page, action, thamSoCanCo) {
	// 🔴 Bấm Tìm kiếm sinh HAI request liên tiếp: một cái KHÔNG mang bộ lọc (RTK Query bắn lại
	//    truy vấn cũ khi `refetch`), rồi mới tới cái mang bộ lọc. Bắt cái đầu là kết luận sai rằng
	//    "bộ lọc không gửi tham số". Vì vậy phải chờ đúng request CÓ tham số cần kiểm.
	const cho = page.waitForRequest(
		(r) => {
			if (!r.url().includes(API_LIST) || r.method() !== 'GET') return false;
			const q = new URL(r.url()).searchParams;
			if (q.get('size') === '1') return false; // truy vấn đếm phiếu giao thẳng
			return thamSoCanCo ? q.has(thamSoCanCo) : true;
		},
		{ timeout: 60_000 },
	);
	await action();
	const req = await cho;
	await settle(page);
	return new URL(req.url()).searchParams;
}

test.describe('04_1 — Theo dõi phiếu đề xuất tự động (vai Tổng công ty)', () => {
	test.beforeEach(async ({ page }) => {
		await openList(page);
	});

	test('04_1_060_001 - Mở màn danh sách Phiếu đề xuất đặt hàng', async ({ page }) => {
		await expect(
			page.locator('.ant-table'),
			'Không mở được bảng danh sách phiếu đề xuất.',
		).toBeVisible();
		const cot = (await page.locator('th').allInnerTexts()).map((x) => x.trim());
		expect(cot, 'Danh sách phải có cột Mã phiếu.').toContain('Mã phiếu');
	});

	test('04_1_060_002 - Phiếu do hệ thống sinh có thẻ Tạo tự động dưới mã phiếu', async ({ page }) => {
		const so = await rows(page).count();
		if (so === 0) skipNoData(test, 'Chưa có phiếu đề xuất nào trong danh sách.');

		// 🔴 `autoGenerated` mới quyết định thẻ này (`StockRequestListPage.jsx:314`), không phải
		//    người tạo. Môi trường có thể chưa có phiếu tự động nào — SKIP kèm lý do, 🚫 đừng
		//    assert "phải có ít nhất một phiếu tự động".
		const theTuDong = page.locator('.ant-table-tbody .ant-tag', { hasText: 'Tạo tự động' });
		if ((await theTuDong.count()) === 0) {
			skipNoData(test, `Danh sách có ${so} phiếu nhưng không phiếu nào do hệ thống tự tạo.`);
		}

		// Thẻ phải nằm trong ô Mã phiếu (cột 2), không phải cột khác.
		const oMaPhieu = rows(page).first().locator('td').nth(1);
		await expect(
			theTuDong.first(),
			'Thẻ Tạo tự động phải hiển thị được.',
		).toBeVisible();
		expect(
			await oMaPhieu.count(),
			'Không đọc được cột Mã phiếu để đối chiếu vị trí thẻ.',
		).toBe(1);
	});

	test('04_1_060_003 - Lọc theo Mã phiếu', async ({ page }) => {
		if ((await rows(page).count()) === 0) skipNoData(test, 'Chưa có phiếu nào để lọc.');
		const ma = (await rows(page).first().locator('td').nth(1).innerText()).trim().split('\n')[0];

		// 🔴 Bộ lọc màn này KHÔNG tự chạy khi đổi giá trị: `<Form onFinish={handleSearch}>` chỉ gọi
		//    API khi bấm nút **Tìm kiếm** (`htmlType="submit"`). Đổi ô rồi chờ request là chờ vô ích
		//    tới hết timeout. Ô Mã phiếu là `Form.Item name="keyword"`, placeholder "VD: DX2606188137".
		const q = await locBy(
			page,
			async () => {
				await page.getByLabel('Mã phiếu', { exact: false }).first().fill(ma);
				await page.getByRole('button', { name: 'Tìm kiếm' }).first().click();
			},
			'keyword',
		);
		expect(
			[...q.values()].join(' '),
			`Lọc mã "${ma}" mà request không mang từ khoá nào.`,
		).toContain(ma);

		const so = await rows(page).count();
		if (so === 0) skipNoData(test, `Lọc mã "${ma}" không ra dòng nào.`);
		for (let i = 0; i < so; i++) {
			await expect(
				rows(page).nth(i).locator('td').nth(1),
				`Lọc mã "${ma}" mà danh sách còn dòng khác mã.`,
			).toContainText(ma);
		}
	});

	test('04_1_060_004 - Lọc theo Trạng thái', async ({ page }) => {
		// Ô Trạng thái là `Form.Item name="status"`, placeholder "Tất cả trạng thái".
		const loc = page.locator('.ant-select').filter({ hasText: /Tất cả trạng thái/i }).first();
		if ((await loc.count()) === 0) skipNoData(test, 'Màn không có bộ lọc Trạng thái.');

		await loc.click();
		const opt = page.locator('.ant-select-dropdown:visible .ant-select-item-option');
		await expect
			.poll(() => opt.count(), { message: 'Bộ lọc Trạng thái không có lựa chọn.', timeout: 20_000 })
			.toBeGreaterThan(0);
		const nhan = (await opt.first().innerText()).trim();
		await opt.first().click();

		// 🔴 Chọn xong vẫn phải bấm Tìm kiếm — xem chú thích ở case 060_003.
		const q = await locBy(
			page,
			() => page.getByRole('button', { name: 'Tìm kiếm' }).first().click(),
			'status',
		);
		expect(
			[...q.keys()].join(' '),
			`Chọn Trạng thái "${nhan}" mà request không mang tham số trạng thái.`,
		).toMatch(/status|state/i);
	});

	test('04_1_060_005 - Lọc theo Khoảng thời gian', async ({ page }) => {
		const picker = page.locator('.ant-picker').first();
		if ((await picker.count()) === 0) skipNoData(test, 'Màn không có ô chọn khoảng thời gian.');

		await picker.click();
		const preset = page
			.locator('.ant-picker-dropdown:visible .ant-picker-preset, .ant-picker-dropdown:visible .ant-tag')
			.first();
		if ((await preset.count()) === 0) {
			await page.keyboard.press('Escape');
			skipNoData(test, 'Ô chọn khoảng thời gian không có lựa chọn dựng sẵn để bấm.');
		}

		await preset.click();
		const q = await locBy(page, () =>
			page.getByRole('button', { name: 'Tìm kiếm' }).first().click(),
		);
		expect(
			[...q.keys()].join(' '),
			'Đổi khoảng thời gian mà request không mang tham số thời gian.',
		).toMatch(/time|date|from|to/i);
	});

	test('04_1_060_006 - Mở chi tiết phiếu xem mặt hàng và số lượng', async ({ page }) => {
		if ((await rows(page).count()) === 0) skipNoData(test, 'Chưa có phiếu nào để mở chi tiết.');

		await rows(page).first().locator('td').nth(1).locator('div').first().click();
		await expect
			.poll(() => page.url(), {
				message: 'Bấm mã phiếu không mở được màn chi tiết.',
				timeout: 30_000,
			})
			.toMatch(/purchase-request\/detail|stock-request/i);
		await settle(page);

		await expect(
			page.locator('.ant-table').first(),
			'Màn chi tiết phải có bảng mặt hàng.',
		).toBeVisible();
	});
});
