const { chromium } = require("playwright");
require("./tai-lieu-test/shared/config");
const { storageStateFor } = require("./tai-lieu-test/shared/auth/accounts");
const kk = require("./tai-lieu-test/04_4_kiem_kho/tests/kiem-kho-ghi");
const k = require("./tai-lieu-test/04_3_nhap_xuat_chuyen_kho/tests/ghi-kho");
const ExcelJS=require('exceljs');
(async()=>{const b=await chromium.launch();const c=await b.newContext({storageState:storageStateFor("shop"),viewport:{width:1440,height:1000}});const page=await c.newPage();
const st=k.batHeader(page);
page.on('response',async r=>{if(/inventory-check/.test(r.url())&&r.request().method()!=='GET')console.log('RES',r.request().method(),r.url().slice(40,160),(await r.text().catch(()=>'')).slice(0,700))});
const sid=await kk.moPhien(page,'shop'); const tid=await kk.themPhieu(page);
const wb=new ExcelJS.Workbook(); const ws=wb.addWorksheet('inventory_check');
ws.addRow(["SKU","Tên sản phẩm","Tên biến thể","Đơn vị","PP tính giá vốn","Mã lô","Tồn kho","Tồn kho thực tế","Serial","Ghi chú"]);
ws.addRow(["AUTO8_SKU_FIFO","AUTO8_SP_FIFO","Mặc định","Cái","Nhập trước xuất trước","AUTO8_LO_FIFO",100,101,"",""]);
ws.addRow(["AUTO8_SKU_FIFO","AUTO8_SP_FIFO","Mặc định","Cái","Nhập trước xuất trước","",100,100,"",""]);
ws.addRow(["KHONGCO_SKU","KHONG_CO_SP","Mặc định","Cái","","",0,5,"",""]);
ws.addRow(["","AUTO8_SP_TC","Mặc định","Cái","Giá tiêu chuẩn","",208,208,"",""]);
await wb.xlsx.writeFile('/private/tmp/claude-501/pr/kk.xlsx');
await page.getByRole('button',{name:'Nhập từ Excel'}).click(); await page.waitForTimeout(1500);
const d=page.locator('.ant-drawer-open, .ant-modal-wrap:visible').last(); console.log(await d.innerText());
await d.locator('input[type=file]').setInputFiles('/private/tmp/claude-501/pr/kk.xlsx'); await page.waitForTimeout(1500); await d.getByRole('button',{name:'Nhập dữ liệu'}).click(); await page.waitForTimeout(6000); console.log('ROWS',await page.locator('tr[data-row-key]').allInnerTexts());
console.log(await page.locator('.ant-drawer-open, .ant-modal-wrap:visible').last().innerText().then(t=>t.slice(0,1500)));
console.log(await page.locator('.ant-message').allInnerTexts());
await kk.huyPhien(page,st,68152,sid); await b.close()})();
