const { chromium } = require("playwright");
require("./tai-lieu-test/shared/config");
const { storageStateFor } = require("./tai-lieu-test/shared/auth/accounts");
const { moTrang } = require("./tai-lieu-test/shared/auth/login");
(async()=>{const b=await chromium.launch();const c=await b.newContext({storageState:storageStateFor("tct"),viewport:{width:1440,height:1000}});const page=await c.newPage();
await page.route('**/__api/**', async (route)=>{const r=route.request(); if(r.method()!=='GET' && /scope|freeze/i.test(r.url())){console.log('BLOCK',r.url().slice(40),r.postData()); return route.fulfill({status:200,contentType:'application/json',body:'{"status":{"code":"403"}}'});} return route.continue();});
await moTrang(page,process.env.VNPOST_BASE_URL+'/settings?setting=stockFreeze','tct'); await page.waitForTimeout(3000);
await page.getByRole('button',{name:'Thêm cấu hình khoá kho'}).click();
const d=page.locator('.ant-drawer-open').last();
await d.locator('.ant-radio-wrapper').filter({hasText:/Điểm bán/}).first().click(); await page.waitForTimeout(500);
console.log('radio checked:', await d.locator('.ant-radio-wrapper-checked').allInnerTexts());
await d.getByPlaceholder('Tìm kiếm').first().fill('AUTO8_TINH'); await page.waitForTimeout(1200);
await d.getByText('AUTO8_TINH',{exact:true}).first().click(); await page.waitForTimeout(1200);
await d.getByText('AUTO8_XA',{exact:true}).first().click(); await page.waitForTimeout(1200);
const o=d.locator('.sp-item').filter({has:page.getByRole('button',{name:'AUTO8_SHOP',exact:true})}).first();
console.log('sp-item html', (await o.innerHTML()).slice(0,500));
await o.locator('.ant-checkbox-input, input[type=checkbox]').first().check({force:true}); await page.waitForTimeout(800);
console.log('checked items:', await d.locator('.sp-item:has(.ant-checkbox-checked)').allInnerTexts(), (await d.innerText()).match(/Đã chọn[^|\n]*\n?[^\n]*/)?.[0]);
await d.getByRole('button',{name:'Áp dụng khoá kho'}).click(); await page.waitForTimeout(3000);
await b.close()})();
